Update generate_wheels.yml

diff --git a/.github/workflows/generate_wheels.yml b/.github/workflows/generate_wheels.yml
--- a/.github/workflows/generate_wheels.yml
+++ b/.github/workflows/generate_wheels.yml
@@ -8,13 +8,19 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, windows-latest, macos-latest]
+        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
+
+      # Used to host cibuildwheel
+      - uses: actions/setup-python@v5
+
+      - name: Install cibuildwheel
+        run: python -m pip install cibuildwheel==2.21.2
 
       - name: Build wheels
-        uses: pypa/cibuildwheel@v1.12.0
+        run: python -m cibuildwheel --output-dir wheelhouse  || echo "FAILED in wheel creation"
         # to supply options, put them in 'env', like:
         # env:
         #   CIBW_SOME_OPTION: value
